//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFuncionarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}
