//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFuncionarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public Nullable<int> Departamento_id { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
